---
title: "Supplementary Materials for semi-BART paper"
author: "Bret Zeldow"
date: "3/6/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This git repository is to house supplementary materials -- mostly R code -- for the paper "A semiparametric modeling approach using Bayesian Additive Regression Trees with an application to evaluate heterogeneous treatment effects" by Bret Zeldow, Vincent Lo Re III, and Jason Roy. The arxiv version is available [here](https://arxiv.org/abs/1806.04200). We will update the link when accepted to a journal. The code to implement our method is available at https://www.github.com/zeldow/semibart. Our code is based off of the [BayesTree package](https://cran.r-project.org/web/packages/BayesTree/index.html).

## What's included?

As of March 6, 2019, this git repository will house the simulation code (data-generating and analaysis), real data analysis code, and miscellaneous simulation code. The simulation code is organized by table number in the manuscript (section 4). The analysis code is the code used to analyze the HIV/HCV data (section 5). Please note that I did not include the analysis dataset because I do not have permission to post it publicly. The miscellaneous simulation code is ancillary code that we used to examine bias estimates when data are simulated with a tree-structure (in the manuscript, we talk about this in the last two paragraphs of section 3.3). 

## Contact

Please contact Bret Zeldow with any questions, complaints, requests, etc. via email: zeldow [at] pm [dot] me.